// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PersonRoot

@interface PersonRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_Sex = 2,
  Person_FieldNumber_Age = 3,
};

@interface Person : GPBMessage

//姓名
@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

//性别
@property(nonatomic, readwrite) BOOL hasSex;
@property(nonatomic, readwrite) int32_t sex;

//年龄
@property(nonatomic, readwrite) BOOL hasAge;
@property(nonatomic, readwrite) int32_t age;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
